name: pull request

on: [pull_request, workflow_dispatch]

jobs:
  code_checks:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
      - name: Install deps
        run: npm ci
      - name: Code Checks
        run: npm run prepublishOnly

  publish_npm_betas:
    name: Publish NPM beta versions
    runs-on: ubuntu-latest
    needs: [check_fork]
    if: needs.check_fork.outputs.is_not_fork == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
      - name: Install deps
        run: npm ci
      - name: Get git branch
        id: git-branch
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD | cut -d'/' -f2 )"
      - name: Get git commit
        id: git-commit
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - name: NPM version
        env:
          SHA: ${{ steps.git-commit.outputs.sha }}
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          npm version $PACKAGE_VERSION-pr.$SHA
      - name: Setup .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - name: Publish to NPM
        run: npm publish --tag pr
